device: cuda
velorange:
  - 0
  - -40
  - -3
  - 70.4
  - 40
  - 1
voxelshape:
  - 352
  - 400
  - 10
carsize: # it's a temp param, the model only supports detect cars currenly
  - 3.9
  - 1.6
  - 1.56
batchsize: 1 # this param doesn't work because the model currenly supports only batchsize=1
bnaffine: False # whether to use trainable BN layers
bntrack: False # whether to update var and mean in BN
samplenum: 6
numthreads: 16
imsize:
  - 370
  - 1224